export const AGE_PROFILES = [
  {
    min: 15,
    max: 19,
    label: '15-19',
    title: '青年调查员',
    summary: 'STR 与 SIZ 合计减少 5 点，EDU 减少 5 点，Luck 建议重掷两次取高。',
    manualNotes: [
      'STR 与 SIZ 的 5 点减值需要玩家自行分配。',
      '这段年龄的修正更适合先预览，再手动微调。',
    ],
    movPenalty: 0,
    educationChecks: 0,
    appPenalty: 0,
    physicalPenalty: 5,
    autoPenalty: {
      EDU: 5,
    },
    manualPenalty: {
      total: 5,
      keys: ['STR', 'SIZ'],
    },
    luckRerolls: 2,
  },
  {
    min: 20,
    max: 39,
    label: '20-39',
    title: '成年调查员',
    summary: '无年龄属性修正。',
    manualNotes: ['默认不产生年龄减值。'],
    movPenalty: 0,
    educationChecks: 0,
    appPenalty: 0,
    physicalPenalty: 0,
    autoPenalty: {},
    manualPenalty: null,
    luckRerolls: 0,
  },
  {
    min: 40,
    max: 49,
    label: '40-49',
    title: '中年调查员',
    summary: '教育成长检定 1 次，STR/CON/DEX 合计减少 5 点，APP 减少 5 点，MOV 减少 1。',
    manualNotes: ['STR/CON/DEX 的 5 点减值建议优先分配给体能较高的属性。'],
    movPenalty: 1,
    educationChecks: 1,
    appPenalty: 5,
    physicalPenalty: 5,
    autoPenalty: {
      APP: 5,
    },
    manualPenalty: {
      total: 5,
      keys: ['STR', 'CON', 'DEX'],
    },
    luckRerolls: 0,
  },
  {
    min: 50,
    max: 59,
    label: '50-59',
    title: '成熟调查员',
    summary: '教育成长检定 2 次，STR/CON/DEX 合计减少 10 点，APP 减少 10 点，MOV 减少 2。',
    manualNotes: ['STR/CON/DEX 的 10 点减值建议按你的设定分配。'],
    movPenalty: 2,
    educationChecks: 2,
    appPenalty: 10,
    physicalPenalty: 10,
    autoPenalty: {
      APP: 10,
    },
    manualPenalty: {
      total: 10,
      keys: ['STR', 'CON', 'DEX'],
    },
    luckRerolls: 0,
  },
  {
    min: 60,
    max: 69,
    label: '60-69',
    title: '高龄调查员',
    summary: '教育成长检定 3 次，STR/CON/DEX 合计减少 20 点，APP 减少 15 点，MOV 减少 3。',
    manualNotes: ['20 点体能减值可以按角色背景自由分配。'],
    movPenalty: 3,
    educationChecks: 3,
    appPenalty: 15,
    physicalPenalty: 20,
    autoPenalty: {
      APP: 15,
    },
    manualPenalty: {
      total: 20,
      keys: ['STR', 'CON', 'DEX'],
    },
    luckRerolls: 0,
  },
  {
    min: 70,
    max: 79,
    label: '70-79',
    title: '暮年调查员',
    summary: '教育成长检定 4 次，STR/CON/DEX 合计减少 40 点，APP 减少 20 点，MOV 减少 4。',
    manualNotes: ['高龄段的体能减值很重，建议优先保留角色核心概念。'],
    movPenalty: 4,
    educationChecks: 4,
    appPenalty: 20,
    physicalPenalty: 40,
    autoPenalty: {
      APP: 20,
    },
    manualPenalty: {
      total: 40,
      keys: ['STR', 'CON', 'DEX'],
    },
    luckRerolls: 0,
  },
  {
    min: 80,
    max: 200,
    label: '80+',
    title: '耄耋调查员',
    summary: '教育成长检定 4 次，STR/CON/DEX 合计减少 80 点，APP 减少 25 点，MOV 减少 5。',
    manualNotes: ['80 岁以上建议将重点放在故事性与调查能力上。'],
    movPenalty: 5,
    educationChecks: 4,
    appPenalty: 25,
    physicalPenalty: 80,
    autoPenalty: {
      APP: 25,
    },
    manualPenalty: {
      total: 80,
      keys: ['STR', 'CON', 'DEX'],
    },
    luckRerolls: 0,
  },
];

export const FALLBACK_EXPERIENCE_PACKS = [
  {
    id: 'battle-soldier',
    name: '战场经历包（普通士兵）',
    sanityLoss: '1D10+5',
    initialAge: '自行调整',
    skillGrowth: '70',
    backgroundAdd: '战争相关的伤疤/疤痕或恐惧症/躁狂症',
    skills: '攀爬，格斗(斗殴)，射击(步霰)，急救，恐吓，聆听，潜行，投掷，妙手，侦查，生存',
    notes: '对目击尸体和重伤员造成的理智损失免疫',
  },
  {
    id: 'battle-officer',
    name: '战场经历包（军官）',
    sanityLoss: '1D10+5',
    initialAge: '自行调整',
    skillGrowth: '70',
    backgroundAdd: '战争相关的伤疤/疤痕或恐惧症/躁狂症',
    skills: '攀爬，格斗(斗殴)，射击(手枪)，急救，聆听，导航/取悦/说服/恐吓 中一项，潜行，投掷，侦查',
    notes: '对目击尸体和重伤员造成的理智损失免疫',
  },
  {
    id: 'police',
    name: '警务经历包',
    sanityLoss: '1D10',
    initialAge: '>=25',
    skillGrowth: '60',
    backgroundAdd: '警察工作相关的伤疤/疤痕或恐惧症/躁狂症',
    skills: '攀爬，汽车驾驶，格斗(斗殴)，射击(手枪或步霰)，急救，法律，聆听，语言，两项社交技能(取悦/话术/说服/恐吓)，追踪',
    notes: '对目击尸体造成的理智损失免疫',
  },
  {
    id: 'criminal',
    name: '罪犯经历包',
    sanityLoss: '1D10',
    initialAge: '>=20',
    skillGrowth: '60',
    backgroundAdd: '犯罪历史相关的伤疤/疤痕或恐惧症/躁狂症',
    skills: '攀爬，汽车驾驶，格斗(任一)，射击(任一)，一项社交技能(取悦/话术/说服/恐吓)，法律，聆听，锁匠，心理学，追踪',
    notes: '对目击尸体、目击或亲自谋杀、目击对人类的暴力残害造成的理智损失免疫',
  },
  {
    id: 'medical',
    name: '医务经历包',
    sanityLoss: '1D10',
    initialAge: '>=30',
    skillGrowth: '60',
    backgroundAdd: '个人背景相关的伤疤/疤痕或恐惧症/躁狂症',
    skills: '急救，法律，聆听，医学，心理学，侦查，科学(任二)',
    notes: '对目击尸体和重伤员造成的理智损失免疫',
  },
  {
    id: 'mythos',
    name: '神话经历包',
    sanityLoss: 'CM',
    initialAge: '自行调整',
    skillGrowth: '自定义',
    backgroundAdd: '神话经历相关的伤疤/疤痕或恐惧症/躁狂症、遭遇的怪异存在',
    skills: '克苏鲁神话',
    notes: '经过 KP 同意后，“相信者”可以习得法术。',
  },
  {
    id: 'custom',
    name: '自定义经历包',
    sanityLoss: '',
    initialAge: '',
    skillGrowth: '',
    backgroundAdd: '',
    skills: '',
    notes: '由 KP 与玩家协商填入。',
  },
];

export const SPENDING_LEVEL_TABLE = [
  { min: 0, max: 0, level: '身无分文', spending: '$0.5/日', cash: '$0.50', assets: '无' },
  { min: 1, max: 9, level: '贫困', spending: '$1-2/日', cash: (cr) => `$${cr}`, assets: (cr) => `$${cr * 10}` },
  { min: 10, max: 49, level: '平均', spending: '$5-10/日', cash: (cr) => `$${cr * 2}`, assets: (cr) => `$${cr * 50}` },
  { min: 50, max: 89, level: '富裕', spending: '$50-100/日', cash: (cr) => `$${cr * 5}`, assets: (cr) => `$${cr * 500}` },
  { min: 90, max: 98, level: '豪富', spending: '$250+/日', cash: (cr) => `$${cr * 20}`, assets: (cr) => `$${cr * 2000}` },
  { min: 99, max: 99, level: '超级富豪', spending: '无上限', cash: '$50,000', assets: '$5,000,000+' },
];

export function getAgeProfile(age) {
  const n = Number.parseInt(age, 10);
  const safeAge = Number.isFinite(n) ? n : 0;
  return (
    AGE_PROFILES.find((profile) => safeAge >= profile.min && safeAge <= profile.max) || {
      min: 0,
      max: 0,
      label: '未知',
      title: '未知年龄段',
      summary: '无法识别年龄段。',
      manualNotes: [],
      movPenalty: 0,
      educationChecks: 0,
      appPenalty: 0,
      physicalPenalty: 0,
      autoPenalty: {},
      manualPenalty: null,
      luckRerolls: 0,
    }
  );
}
