export const STAGES = [
  { label: "序章", title: "角色身份", goal: "先在职业图鉴中选择职业，再填写调查员基础信息。" },
  { label: "第一章", title: "属性骰点", goal: "按 CoC7 规则生成属性并确认衍生值。" },
  { label: "第二章", title: "技能分配", goal: "按职业规则完成职业技能可选项，再手动分配点数。" },
  { label: "第三章", title: "背景装备", goal: "补完背景并拖拽武器到角色卡。" },
  { label: "终章", title: "导出收尾", goal: "导出精简 PDF 与模板兼容 Excel。" },
];

export const ATTR_ORDER = ["STR", "CON", "POW", "DEX", "APP", "SIZ", "INT", "EDU", "Luck"];

export const SKILL_DEFS = [
  { key: "accounting", name: "会计", base: 5 },
  { key: "anthropology", name: "人类学", base: 1 },
  { key: "animalHandling", name: "驯兽", base: 5 },
  { key: "appraise", name: "估价", base: 5 },
  { key: "archaeology", name: "考古学", base: 1 },
  { key: "artillery", name: "炮术", base: 1 },
  { key: "artCraft", name: "艺术/工艺", base: 5 },
  { key: "charm", name: "魅惑", base: 15 },
  { key: "climb", name: "攀爬", base: 20 },
  { key: "computerUse", name: "计算机使用", base: 5 },
  { key: "creditRating", name: "信用评级", base: 0 },
  { key: "cthulhuMythos", name: "克苏鲁神话", base: 0 },
  { key: "demolitions", name: "爆破", base: 1 },
  { key: "disguise", name: "乔装", base: 5 },
  { key: "dive", name: "潜水", base: 1 },
  { key: "dodge", name: "闪避", base: 0 },
  { key: "driveAuto", name: "汽车驾驶", base: 20 },
  { key: "elecRepair", name: "电气维修", base: 10 },
  { key: "electronics", name: "电子学", base: 1 },
  { key: "fastTalk", name: "话术", base: 5 },
  { key: "fightingBrawl", name: "格斗(斗殴)", base: 25 },
  { key: "firearmsHandgun", name: "射击(手枪)", base: 20 },
  { key: "firearmsRifle", name: "射击(步枪/霰弹枪)", base: 25 },
  { key: "firstAid", name: "急救", base: 30 },
  { key: "history", name: "历史", base: 5 },
  { key: "hypnosis", name: "催眠", base: 1 },
  { key: "intimidate", name: "恐吓", base: 15 },
  { key: "jump", name: "跳跃", base: 20 },
  { key: "knowledge", name: "学识", base: 1 },
  { key: "languageOther", name: "其他语言", base: 1 },
  { key: "languageOwn", name: "母语", base: 0 },
  { key: "law", name: "法律", base: 5 },
  { key: "libraryUse", name: "图书馆使用", base: 20 },
  { key: "lipReading", name: "读唇", base: 1 },
  { key: "listen", name: "聆听", base: 20 },
  { key: "locksmith", name: "锁匠", base: 1 },
  { key: "mechRepair", name: "机械维修", base: 10 },
  { key: "medicine", name: "医学", base: 1 },
  { key: "naturalWorld", name: "博物学", base: 10 },
  { key: "navigate", name: "导航", base: 10 },
  { key: "occult", name: "神秘学", base: 5 },
  { key: "operateHeavyMachinery", name: "操作重型机械", base: 1 },
  { key: "pilot", name: "操作/驾驶", base: 1 },
  { key: "persuade", name: "说服", base: 10 },
  { key: "psychoanalysis", name: "精神分析", base: 1 },
  { key: "psychology", name: "心理学", base: 10 },
  { key: "ride", name: "骑术", base: 5 },
  { key: "science", name: "科学", base: 1 },
  { key: "sleightOfHand", name: "妙手", base: 10 },
  { key: "spotHidden", name: "侦查", base: 25 },
  { key: "stealth", name: "潜行", base: 20 },
  { key: "survival", name: "生存", base: 10 },
  { key: "swim", name: "游泳", base: 20 },
  { key: "throw", name: "投掷", base: 20 },
  { key: "track", name: "追踪", base: 10 },
];

export const SKILL_ALIAS = {
  accounting: ["会计"],
  anthropology: ["人类学"],
  animalHandling: ["驯兽", "驯养"],
  appraise: ["估价"],
  archaeology: ["考古学"],
  artillery: ["炮术"],
  artCraft: ["技艺", "艺术", "工艺", "艺术工艺", "技艺表演", "技艺(任一)", "技艺（任一）"],
  charm: ["魅惑", "取悦"],
  climb: ["攀爬"],
  computerUse: ["计算机使用", "计算机"],
  creditRating: ["信用评级", "信用"],
  cthulhuMythos: ["克苏鲁神话", "神话"],
  demolitions: ["爆破"],
  disguise: ["乔装"],
  dive: ["潜水"],
  dodge: ["闪避"],
  driveAuto: ["汽车驾驶", "驾驶(汽车)", "驾驶汽车"],
  elecRepair: ["电气维修", "电子维修"],
  electronics: ["电子学"],
  fastTalk: ["话术"],
  fightingBrawl: ["格斗", "格斗斗殴", "格斗(斗殴)", "斗殴"],
  firearmsHandgun: ["射击", "射击手枪", "射击(手枪)", "手枪"],
  firearmsRifle: ["射击", "射击步枪霰弹枪", "射击(步枪/霰弹枪)", "步枪", "霰弹枪"],
  firstAid: ["急救"],
  history: ["历史"],
  hypnosis: ["催眠"],
  intimidate: ["恐吓"],
  jump: ["跳跃"],
  knowledge: ["学识"],
  languageOther: ["其他语言", "外语", "外国语言"],
  languageOwn: ["母语"],
  law: ["法律"],
  libraryUse: ["图书馆使用", "图书馆"],
  lipReading: ["读唇"],
  listen: ["聆听"],
  locksmith: ["锁匠", "开锁"],
  mechRepair: ["机械维修"],
  medicine: ["医学"],
  naturalWorld: ["博物学"],
  navigate: ["导航"],
  occult: ["神秘学"],
  operateHeavyMachinery: ["操作重型机械"],
  pilot: ["操作驾驶", "操作", "驾驶", "飞行器", "船"],
  persuade: ["说服"],
  psychoanalysis: ["精神分析"],
  psychology: ["心理学"],
  ride: ["骑术"],
  science: ["科学"],
  sleightOfHand: ["妙手"],
  spotHidden: ["侦查", "观察"],
  stealth: ["潜行", "隐匿"],
  survival: ["生存"],
  swim: ["游泳"],
  throw: ["投掷"],
  track: ["追踪"],
};

export const SKILL_SPECIALIZATION_OPTIONS = {
  artCraft: ["表演", "绘画", "雕刻", "摄影", "写作", "舞蹈", "乐器", "理发", "厨艺", "伪造"],
  languageOther: ["英语", "法语", "德语", "拉丁语", "汉语", "日语", "阿拉伯语", "俄语", "西班牙语", "意大利语"],
  languageOwn: ["英语", "汉语", "法语", "德语", "日语", "俄语", "西班牙语"],
  pilot: ["飞行器", "船", "飞艇", "热气球"],
  science: ["化学", "物理", "生物学", "药学", "数学", "地质学", "天文学", "植物学", "动物学", "密码学", "气象学", "工程学", "司法科学"],
  firearmsHandgun: ["左轮手枪", "半自动手枪", "冲锋枪", "信号枪", "机枪", "重武器"],
  firearmsRifle: ["步枪", "霰弹枪", "弓", "弩", "喷射器"],
  fightingBrawl: ["斗殴", "剑", "斧", "矛", "鞭", "连枷", "绞索", "链锯"],
  survival: ["沙漠", "极地", "海上", "森林", "高山", "丛林", "地底"],
};

export const FALLBACK_OCCUPATIONS_RAW = [
  { name: "私家侦探", formula: "EDU*2+DEX*2", skillText: "法律、图书馆使用、聆听、心理学、侦查、话术、格斗(斗殴)、任意二项" },
  { name: "警探", formula: "EDU*2+DEX*2", skillText: "法律、聆听、心理学、侦查、射击(手枪)、话术、格斗(斗殴)、任意二项" },
  { name: "巡警", formula: "EDU*2+STR*2", skillText: "法律、聆听、心理学、侦查、射击(手枪)、格斗(斗殴)、急救、任意一项" },
  { name: "记者", formula: "EDU*4", skillText: "图书馆使用、历史、话术、心理学、侦查、任意三项" },
  { name: "士兵", formula: "EDU*2+STR*2", skillText: "攀爬、急救、聆听、射击(步枪/霰弹枪)、格斗(斗殴)、任意二项" },
];

export const FALLBACK_WEAPONS = [
  { id: "w-pistol", name: "手枪", type: "远程", skill: "射击(手枪)", damage: "1D10", range: "15码" },
  { id: "w-rifle", name: "步枪", type: "远程", skill: "射击(步枪/霰弹枪)", damage: "2D6+4", range: "110码" },
  { id: "w-knife", name: "小刀", type: "近战", skill: "格斗(斗殴)", damage: "1D4+DB", range: "-" },
];

export const OCCUPATION_QUERY_EXPANSIONS = {
  警察: ["警探", "巡警", "刑警", "侦探", "执法", "警务", "公安"],
  医生: ["医师", "外科", "内科", "药剂师", "精神病学家"],
  老师: ["教师", "教授", "讲师", "研究员"],
  律师: ["法官", "检察官", "法务"],
  记者: ["媒体", "摄影记者", "新闻"],
};

export const OCCUPATION_KEYWORD_GROUPS = [
  { include: ["警探", "巡警", "刑警", "警察", "执法"], keywords: OCCUPATION_QUERY_EXPANSIONS.警察 },
  { include: ["医生", "医师", "药剂师", "精神病学家"], keywords: OCCUPATION_QUERY_EXPANSIONS.医生 },
  { include: ["教师", "老师", "教授", "讲师", "研究员"], keywords: OCCUPATION_QUERY_EXPANSIONS.老师 },
  { include: ["律师", "法官", "检察官"], keywords: OCCUPATION_QUERY_EXPANSIONS.律师 },
  { include: ["记者", "摄影记者", "新闻"], keywords: OCCUPATION_QUERY_EXPANSIONS.记者 },
];
