// 导出到 Excel 的单元格映射配置

export const SKILL_EXPORT_ROWS = {
  accounting: { side: 'left', row: 16 },
  anthropology: { side: 'left', row: 17 },
  appraise: { side: 'left', row: 18 },
  archaeology: { side: 'left', row: 19 },
  artCraft: { side: 'left', row: 20, specializationCell: 'N' },
  charm: { side: 'left', row: 23 },
  climb: { side: 'left', row: 24 },
  computerUse: { side: 'left', row: 25 },
  creditRating: { side: 'left', row: 26 },
  cthulhuMythos: { side: 'left', row: 27 },
  disguise: { side: 'left', row: 28 },
  dodge: { side: 'left', row: 29 },
  driveAuto: { side: 'left', row: 30 },
  elecRepair: { side: 'left', row: 31 },
  electronics: { side: 'left', row: 32 },
  fastTalk: { side: 'left', row: 33 },
  fightingBrawl: { side: 'left', row: 34, specializationCell: 'N' },
  firearmsHandgun: { side: 'left', row: 38, specializationCell: 'N' },
  firearmsRifle: { side: 'left', row: 39, specializationCell: 'N' },
  firstAid: { side: 'left', row: 42 },
  history: { side: 'left', row: 43 },
  intimidate: { side: 'left', row: 44 },
  jump: { side: 'left', row: 45 },
  languageOther: { side: 'left', row: 46, specializationCell: 'N' },
  languageOwn: { side: 'left', row: 49, specializationCell: 'N' },
  law: { side: 'right', row: 16 },
  libraryUse: { side: 'right', row: 17 },
  listen: { side: 'right', row: 18 },
  locksmith: { side: 'right', row: 19 },
  mechRepair: { side: 'right', row: 20 },
  medicine: { side: 'right', row: 21 },
  naturalWorld: { side: 'right', row: 22 },
  navigate: { side: 'right', row: 23 },
  occult: { side: 'right', row: 24 },
  operateHeavyMachinery: { side: 'right', row: 25 },
  persuade: { side: 'right', row: 26 },
  pilot: { side: 'right', row: 27 },
  psychoanalysis: { side: 'right', row: 28 },
  psychology: { side: 'right', row: 29 },
  ride: { side: 'right', row: 30 },
  science: { side: 'right', row: 31 },
  sleightOfHand: { side: 'right', row: 34 },
  spotHidden: { side: 'right', row: 35 },
  stealth: { side: 'right', row: 36 },
  survival: { side: 'right', row: 37 },
  swim: { side: 'right', row: 38 },
  throw: { side: 'right', row: 39 },
  track: { side: 'right', row: 40 },
  animalHandling: { side: 'right', row: 41 },
  dive: { side: 'right', row: 42 },
  demolitions: { side: 'right', row: 43 },
  lipReading: { side: 'right', row: 44 },
  hypnosis: { side: 'right', row: 45 },
  artillery: { side: 'right', row: 46 },
  knowledge: { side: 'right', row: 47 },
};

export const KEY_LINK_CELL_MAP = {
  信念: 'V64',
  重要之人: 'V66',
  意义之地: 'V68',
  珍视之物: 'V70',
  特质: 'V72',
};

export const LEFT_COLUMNS = { occPts: 'R', intPts: 'S' };
export const RIGHT_COLUMNS = { occPts: 'AC', intPts: 'AD' };

export const ATTRIBUTE_INPUT_CELLS = {
  STR: { base: 'W3' },
  DEX: { base: 'Z3' },
  INT: { base: 'AC3' },
  CON: { base: 'W5' },
  APP: { base: 'Z5' },
  POW: { base: 'AC5' },
  SIZ: { base: 'W7' },
  EDU: { base: 'Z7' },
  Luck: { base: 'V10' },
};

export const SPECIALIZATION_CELL_MAP = {
  artCraft: 'N20',
  fightingBrawl: 'N34',
  firearmsHandgun: 'N38',
  firearmsRifle: 'N39',
  languageOther: 'N46',
  languageOwn: 'N49',
  pilot: 'Z27',
  science: 'Z31',
  survival: 'Z37',
};
